@startuml DiagramaCasosUsoOrganizacion
left to right direction
skinparam style strictuml
skinparam DefaultFontName "Helvetica"
skinparam actor {
    BackgroundColor White
    BorderColor DarkSlateGray
}
skinparam usecase {
    BackgroundColor White
    BorderColor DarkSlateGray
    ArrowColor DarkSlateGray
}
actor "Dueño" as dueno
actor "Manager" as manager

manager <|-- dueno

package "Gestión del Restaurante" {
    usecase crearRestaurante as "crearRestaurante()"
    usecase editarRestaurante as "editarRestaurante()"
    usecase eliminarRestaurante as "eliminarRestaurante()"
    usecase consultarRestaurante as "consultarRestaurante()"
}

package "Gestión de Personal" {
    usecase contratarManager as "contratarManager()"
    usecase despedirManager as "despedirManager()"
    usecase listarManagers as "listarManagers()"
}

dueno --> crearRestaurante
dueno --> editarRestaurante
dueno --> eliminarRestaurante
dueno --> consultarRestaurante
dueno --> contratarManager
dueno --> despedirManager
dueno --> listarManagers

eliminarRestaurante .> consultarRestaurante : <<include>>
editarRestaurante .> consultarRestaurante : <<include>>
despedirManager .> listarManagers : <<include>>
@enduml
